---
title: 'Figures for comment on "Information arms race explains plant-herbivore chemical communication in ecological communities"'
author:
  - Ethan Bass$^1$*
  - Andre Kessler$^1$
output: html_document
  
---

```{r setup,include=F}
knitr::opts_chunk$set(warning=F, echo=F)
required_packages = c('zeallot','xlsx','ggplot2')
install.packages(required_packages[which(!(required_packages %in% installed.packages()))])
library('zeallot')
library('xlsx')
library('ggplot2')

#  load information functions from information_functions.Rmd
source('information_functions.R')
```

Run the code below to download the supplementary files from Zu et al 2020, or download them manually and place them into the "data" directory: 

1) https://www.science.org/doi/suppl/10.1126/science.aba2965/suppl_file/aba2965-zu-sm-database-s1.xlsx

2) https://zenodo.org/record/3743129

```{r, eval=T}
# set eval = T to run
if (!file.exists("data/AP_obs.csv") | !file.exists("data/PV_obs.csv")) {
download.file('https://zenodo.org/record/3743129/files/MITEcology/Science_Zu_et_al_2020-v1.0.zip?download=1', destfile = 'data/zu_data.zip')

unzip('data/zu_data.zip',files=c('MITEcology-Science_Zu_et_al_2020-7aa72bb/AP_obs.csv', 'MITEcology-Science_Zu_et_al_2020-7aa72bb/PV_obs.csv'), exdir = 'data', unzip = getOption("unzip"), junkpaths = T)
 }
if (!file.exists("data/aba2965-zu-sm-database-s1.xlsx")){
download.file('https://www.science.org/doi/suppl/10.1126/science.aba2965/suppl_file/aba2965-zu-sm-database-s1.xlsx', destfile= 'data/aba2965-zu-sm-database-s1.xlsx')}
```

# Neutral model:
```{r, echo=F,warnings=F,eval=T}
# neutral model with spare AP matrix and no selection
# initialize variables
PV = list()
AP = list()
AV <- list()

HPV <- numeric()
HAP <- numeric()
HAV <- numeric()

###
reps=1000
i=1
nA=28
nP=20
nV=31
AP_prob <- c(rep(0,9),1)
AP[[i]] = matrix(sample(AP_prob,nA*nP,replace = T),nA,nP)
##########
PV_prob <- c(0,rep(1,4))
PV[[i]] = matrix(sample(PV_prob,nP*nV,replace = T),nP,nV)
##########
AV[[i]] <- as.matrix(AP[[i]]) %*% as.matrix(PV[[i]])

HAV[i] <- c_entropy(AV[[i]])
HAP[i] <- c_entropy(AP[[i]])
HPV[i] <- c_entropy(PV[[i]])

n=reps
for (i in 2:n){
  PV[[i]] <- PV[[i-1]]
  AP[[i]] <- AP[[i-1]]
  if((i %% 2) == 0){
    #mutate an element of the PV matrix
    PV[[i]] <- PV[[i-1]]
    AP[[i]] <- AP[[i-1]]
    r=sample(c(1:560),1)
    v=sample(PV_prob,1)
    PV[[i]][r] <- v
    AV[[i]] <- AP[[i]] %*% PV[[i]]
  } else{
    #mutate an element of the AP matrix
    r=sample(c(1:560),1)
    v=sample(AP_prob,1)
    AP[[i]][r] <- v
    
    AV[[i]] <- AP[[i]] %*% PV[[i]]
  }
  #calculate conditional entropies
    HAV[i] <- c_entropy(AV[[i]])
    HAP[i] <- c_entropy(AP[[i]])
    HPV[i] <- c_entropy(PV[[i]])
}

#save neutral model
S_neutral <- list(reps,PV,AP,AV,HPV,HAP,HAV)
saveRDS(S_neutral,'data/S_neutral.RDS')
```

```{r, echo=F, eval=T, include=F}
### load field data ###
AP_obs <- read.csv("data/AP_obs.csv", header = TRUE, as.is = TRUE, row.names = 1)
PV_obs <- read.csv("data/PV_obs.csv", header = TRUE, as.is = TRUE, row.names = 1)
AV_obs <- as.matrix(AP_obs) %*% as.matrix(PV_obs)
```

Community fitness model:
```{r, echo=F, eval=F}
# community fitness model
#(this analysis may take a long time to run with 100000 reps -- consider reducing the number of reps to shorten analysis time)

## set parameters

reps <- 100000

## matrix dimensions
nA <- nrow(AP_obs) # number of herbivores
nP <- ncol(AP_obs) # number of plants
nV <- ncol(PV_obs) # number of VOCs

### create data structures to store values
A_PV <- vector('list', 2*reps)  
A_AP  <- vector('list', 2*reps)
A_AV  <- vector('list', 2*reps)

E = matrix(NA, nrow = reps, ncol = 18) # dataset to store variables after each simulation
colnames(E) <- c("N", "E_plant", "E_animal", "H_V", "HPV", "HVP", "HAV", "HVA", "HAP", "HPA",
                 "dFa", "dFa_c", "dFp", "dFp_c", "Fa_n", "Fa_o", "Fp_n","Fp_o")

#########################################

## initialize matrices
{
  n = 1
  AP <- matrix(rbinom(nA*nP,1,0.5),nA,nP)
  PV <- matrix(rbinom(nP*nV,1,0.5),nP,nV)
  AV <- AP %*% PV
  
  c(HPV,HVP,H_V) %<-% H_A_VOC(PV)
  c(HAV,HVA) %<-% as.numeric(H_A_VOC(AV)[1:2])
  c(HAP,HPA) %<-% as.numeric(H_A_VOC(AP)[1:2])
  Fa_n=0; Fa_o=0
  Fp_n=0; Fp_o=0
  dFp=0; dFp_c=0
  dFa=0; dFa_c=0
  
  # fitness function
  E_plant <- HAV
  E_animal <- 1-HVA
  
  #write to E, A_AP, A_PV
  E[n,] <- c(n, E_plant, E_animal, H_V, 
             HPV, HVP, HAV, HVA, HAP, HPA, rep(NA,8))
  A_AP[[n]] <- AP
  A_PV[[n]] <- PV
}

# run simulation
for (n in 2:(reps))
{
  if (n %% 2 == 0){
    ## mutate herbivore matrix (without driving any herbivores to extinction) ##
    repeat{
      ii<-sample(nA,1)
      j<-sample(nP,1)
      AP_n <- AP
      AP_n[ii,j] <- abs(AP_n[ii,j]-1)
      if (min(rowSums(AP_n)) > 0 & min(colSums(AP_n)) > 0 )  break}

      AV_n <- AP_n %*% PV
    
    c(HAV,HVA) %<-% as.numeric(H_A_VOC(AV_n)[1:2])

    E_animal_new <- 1-HVA

    Fa_n <- specific_information(AV_n)[[ii]]
    Fa_o <- specific_information(AV)[[ii]]
    dFa <- Fa_n - Fa_o
    dFa_c <- E_animal_new - E_animal
    
    #####
    # fix mutation if herbivore "fitness" increases #
    if(E_animal_new > E_animal){
      AP <- AP_n
    }
  } else{
    ## Mutate plant matrix (without driving any plants to extinction) ##
    repeat{
      ii <- sample(nP,1)
      j<-sample(nV,1)
      PV_n <- PV
      PV_n[ii,j] <- abs(PV_n[ii,j]-1)
      if (min(rowSums(PV_n)) >0 & min(colSums(PV_n)) >0 )  break}
    
    AV_n <- AP %*% PV_n
    
    c(HAV,HVA) %<-% as.numeric(H_A_VOC(AV_n)[1:2])

    # calculate fitnesses
    E_plant_new <- HAV
    Fp_n <- IApV(AP_n, AV_n, ii)
    Fp_o <- IApV(AP, AV, ii)
    dFp <- Fp_n - Fp_o
    dFp_c <- E_plant_new - E_plant
    
    # fix mutation if plant "fitness" increases
    if(E_plant_new > E_plant){
      PV <- PV_n
    }
  }
  # record results
  AV <- AP %*% PV
  c(HPV,HVP,H_V) %<-% H_A_VOC(PV)
  c(HAV,HVA) %<-% as.numeric(H_A_VOC(AV)[1:2])
  c(HAP,HPA) %<-% as.numeric(H_A_VOC(AP)[1:2])
  
  # fitness function
  E_plant <- HAV
  E_animal <- 1-HVA
  
  # record results
  E[n,] <- c(n, HAV, (1-HVA), H_V, HPV, HVP, HAV, HVA, HAP, HPA, 
                   dFa, dFa_c, dFp, dFp_c, Fa_n, Fa_o, Fp_n, Fp_o)
  A_AP[[n]] <- AP
  A_PV[[n]] <- PV
}
```

```{r, eval=F}
## save output 
S_com <- list(reps, A_PV, A_AP, E)
saveRDS(S_com,'data/S_com_100k.RDS')
```


```{r}
c(reps, A_PV, A_AP, E) %<-% readRDS('data/S_com_100k.RDS')
#plot_results
plot(-1, xlim = c(0,reps), ylim = c(0,1))
HPV <- H_A_VOC(PV_obs)[[1]]
c(HAV,HVA) %<-% as.numeric(H_A_VOC(AV_obs)[1:2])
HAP <- as.numeric(H_A_VOC(AP_obs)[[1]])

## plot observed values as lines
# conditional entropy for PV, AV and AP
abline(h = HPV, lty = "dotted", pch = 8) 
abline(h = HAV, lty = "solid", pch = 8)
abline(h = HAP, lty = "dashed", pch = 8) 
# fitness for animal and plant
abline(h = 1-HVA, col = "blue") 

s <- seq(1,reps,250)
points(cbind(s,E[s,"HPV"]), col = "red", pch = 24)
points(cbind(s,E[s,"HAV"]), col = "red", pch=  21)
points(cbind(s,E[s,"HAP"]), col = "red", pch=  22)
points(cbind(s,E[s,"E_animal"]), col = "blue", pch = 4)
```


***
\newpage

# Figure 1

```{r, dpi=300, fig.cap="**Fig. 1.** (A) Relationship between the specific information $I(P_i|V)$ and the number of herbivores associated with each plant species (F(1,18)= 0.162,p = 0.69, $R^2$=0.009). (B) Relationship between the fitness of the mutated plant species, calculated as $1-I(A_p,V)$ and the community conditional entropy $H(A|V)$, where $I(A_p,V)$ is calculated as the weighted average of the specific information, I(A=a,V) (Equation 3), for the set of herbivores that interact with plant p (p= <0.001, $R^2$=0.27). (C) Relationship between the “fitness” of the mutated herbivore species, calculated as $I(A_j,V)$, and the community conditional entropy H(V|A), where $I(A=a_j,V)$ is the specific information of the mutated herbivore species with respect to VOCs (p<0.001, $R^2=0.96)). (The shaded quadrants in B and C indicate areas where the “community fitness” and the species-level fitness are of opposite sign, indicating that a mutation would be selected fixed in one model, where it would be  and eliminated in the other). (C) Relationship between the specific information I(P_i |V) and the number of herbivores associated with each plant species (p=0.69,R^2=0.009)."}

c(reps, A_PV, A_AP, E) %<-% readRDS('data/S_com_100k.RDS')

#########

m <- rbind(c(1, 1), c(2, 3))
layout(m)
# bottom, left, top, right
par(mar = c(4.1, 4.1, 1.8, 2.1))
pos='topleft'

### panel A ###
par(mar = c(5.1, 4.1, 2.1, 2.1))

plot(specific_information(PV_obs), colSums(AP_obs),
     xlab=expression('Specific information, I(P'[i]*'|V)'),
     ylab='Herbivore number', pch=20, cex=1.3, cex.lab=0.9)
fig_label(" A",'figure',pos, font=2)

### panel B ###

plot(E[seq(2,nrow(E),2),"dFp"], E[seq(2,nrow(E),2),"dFp_c"],
     xlab = expression(Delta *'I(A=A'[p]*',V)'),
     ylab = expression(Delta *'H(A|V)'),
     cex=.7, yaxt='none',xaxt='none',
     cex.lab=0.9, type='n', xlim=c(-0.1, 0.1))
limits = par()$usr
rect(0,0,limits[1],limits[4],col="gray92")
rect(0,0,limits[2],limits[3],col="gray92")
points(E[seq(2,nrow(E),2),"dFp"], E[seq(2,nrow(E),2),"dFp_c"], pch=16, cex=0.7)

axis(2, las=1, cex.axis=0.7)
axis(1, las=2, cex.axis=0.7)
abline(h=0,v=0,lty=2,col='gray')

fig_label(" B",'figure',pos,font=2)

### panel C ###

plot(E[seq(2,nrow(E),2),"dFa"], E[seq(2,nrow(E),2),"dFa_c"],
     xlab = expression(Delta *'I(V, A'[j]*')'),
     ylab = expression(Delta *'H(V|A)'),
     cex=.7, xaxt = 'none', yaxt='none',
     cex.axis=0.7, cex.lab=0.9, type='n')
limits = par()$usr
rect(0,0,limits[1],limits[4],col="gray92")
rect(0,0,limits[2],limits[3],col="gray92")
axis(2, las=1, cex.axis=0.7)
axis(1, las=2, cex.axis=0.7)
points(E[seq(2,nrow(E),2),"dFa"], E[seq(2,nrow(E),2),"dFa_c"], pch=16, cex=0.7)
abline(h=0,v=0,lty='dashed',col='lightgray')
fig_label(" C",'figure',pos, font=2)
```
Linear regression models:

```{r}
m.A<-lm(specific_information(PV_obs) ~ colSums(AP_obs))
summary(m.A)

m.B<-lm(E[,"dFp"] ~ E[,"dFp_c"])
summary(m.B)

m.C<-lm(E[,'dFa'] ~ E[,'dFa_c'])
summary(m.C)

```

# Figure 2 (Neutral model)
```{r,  dpi=300, out.width="60%", out.height="60%", fig.cap="**Fig. 2.** Simulation of neutrally evolving plant-herbivore community, where the probability of a link in the PV and AP matrices is parameterized using frequencies estimated from the field data. We estimate that plant-volatile links occur with a probability of 0.8 and plant-herbivore links occur with a probability of 0.1. Compare with figure 3A in Zu *et al*."}

c(reps,PV,AP,AV,HPV,HAP,HAV) %<-% readRDS('data/S_neutral.RDS')

x <- seq(1,1000,20)
df <- rbind(data.frame(x=x,value=HPV[x],Simulated='H(P|V)'), data.frame(x=x,value=HAP[x],Simulated='H(A|P)'),
      data.frame(x=x,value=HAV[x],Simulated='H(A|V)'))

# insert path to Zu supplement below
# download from: (https://www.science.org/doi/suppl/10.1126/science.aba2965/suppl_file/aba2965-zu-sm-database-s1.xlsx)

path = 'data/aba2965-Zu-SM-Database-S1.xlsx'
AP_obs <- lapply(seq(5,20,2), function(i) read.xlsx(path, i))
PV_obs <- lapply(seq(6,20,2), function(i) read.xlsx(path, i))

HPV_obs <- sapply(PV_obs, function(PV) c_entropy(PV[,-1]))
HAP_obs <- sapply(AP_obs,function(AP) c_entropy(AP[,-1]))

AV_obs <- lapply(1:3, function(i){
  rs<-rowSums(AP_obs[[i]][,-1])
  data.matrix(AP_obs[[i]][,-1]) %*% data.matrix(PV_obs[[i]])
   })

HAV_obs <- sapply(AV_obs,function(AV) c_entropy(AV))

ggplot(df, aes(x=x, y=value, shape=Simulated, color='#ee8169')) +
  geom_point(size=1) + scale_shape_manual(values=c(15,17,19)) +
  geom_hline(aes(yintercept=mean(HPV_obs), linetype = "H(P|V)")) + 
  geom_hline(aes(yintercept=mean(HAP_obs), linetype = "H(A|P)")) + 
  geom_hline(aes(yintercept=mean(HAV_obs), linetype = "H(A|V)")) +

  scale_linetype_manual(name = "Observed",values=c("dashed","solid", "dotted")) +
  ylim(0,1) + theme_classic() + xlab('Time') + ylab('Uncertainty') +
  guides(color="none", shape=guide_legend(override.aes = list(color='#ee8169')))
```

# Species fitness model:

```{r, echo=F, eval=F, include=T}
# simulation with species-level fitness using specific information
#(this analysis may take a long time to run with 100000 reps -- consider reducing the number of reps to shorten analysis time)

## set parameters

reps <- 100000

## matrix dimensions
nA <- nrow(AP_obs) # number of herbivores
nP <- ncol(AP_obs) # number of plants
nV <- ncol(PV_obs) # number of VOCs

### create data structures to store values
A_PV <- vector('list', 2*reps)  
A_AP  <- vector('list', 2*reps)
A_AV  <- vector('list', 2*reps)

E = matrix(NA, nrow = reps, ncol = 18) # dataset to store variables after each simulation
colnames(E) <- c("N", "E_plant", "E_animal", "H_V", "HPV", "HVP", "HAV", "HVA", "HAP", "HPA",
                 "dFa", "dFa_c", "dFp", "dFp_c", "Fa_n", "Fa_o", "Fp_n","Fp_o")

#########################################

## initialize matrices
{
  n = 1
  AP <- matrix(rbinom(nA*nP,1,0.5),nA,nP)
  PV <- matrix(rbinom(nP*nV,1,0.5),nP,nV)
  AV <- AP %*% PV
  
  c(HPV,HVP,H_V) %<-% H_A_VOC(PV)
  c(HAV,HVA) %<-% as.numeric(H_A_VOC(AV)[1:2])
  c(HAP,HPA) %<-% as.numeric(H_A_VOC(AP)[1:2])
  Fa_n=0; Fa_o=0
  Fp_n=0; Fp_o=0
  dFp=0; dFp_c=0
  dFa=0; dFa_c=0
  
  # fitness function
  E_plant <- HAV
  E_animal<- 1-HVA
  
  #write to E, A_AP, A_PV
  E[n,] <- c(n, E_plant, E_animal, H_V, 
             HPV, HVP, HAV, HVA, HAP, HPA, rep(NA,8))
  A_AP[[n]] <- AP
  A_PV[[n]] <- PV
}

# run simulation
for (n in 2:(reps))
{
  if (n %% 2 == 0){
    ## mutate herbivore matrix (without driving any herbivores to extinction) ##
    repeat{
      ii<-sample(nA,1)
      j<-sample(nP,1)
      AP_n <- AP
      AP_n[ii,j] <- abs(AP_n[ii,j]-1)
      if (min(rowSums(AP_n)) > 0 & min(colSums(AP_n)) > 0 )  break}

      AV_n <- AP_n %*% PV
    
    c(HAV,HVA) %<-% as.numeric(H_A_VOC(AV_n)[1:2])

    E_animal_new <- 1-HVA

    Fa_n <- specific_information(AV_n)[[ii]]
    Fa_o <- specific_information(AV)[[ii]]
    dFa <- Fa_n - Fa_o
    dFa_c <- E_animal_new - E_animal
    
    #####
    # fix mutation if herbivore "fitness" increases
    if(dFa > 0){
      AP <- AP_n
    }
  } else{
    ## Mutate plant matrix (without driving any plants to extinction) ##
    repeat{
      ii <- sample(nP,1)
      j<-sample(nV,1)
      PV_n <- PV
      PV_n[ii,j] <- abs(PV_n[ii,j]-1)
      if (min(rowSums(PV_n)) >0 & min(colSums(PV_n)) >0 )  break}
    
    AV_n <- AP %*% PV_n
    
    c(HAV,HVA) %<-% as.numeric(H_A_VOC(AV_n)[1:2])

    # calculate fitnesses
    E_plant_new <- HAV
    Fp_n <- IApV(AP_n, AV_n, ii)
    Fp_o <- IApV(AP, AV, ii)
    dFp <- Fp_n - Fp_o
    dFp_c <- E_plant_new - E_plant
    
    # fix mutation if plant "fitness" increases
    if(dFp > 0){
      PV <- PV_n
    }
  }
  # record results
  AV <- AP %*% PV
  c(HPV,HVP,H_V) %<-% H_A_VOC(PV)
  c(HAV,HVA) %<-% as.numeric(H_A_VOC(AV)[1:2])
  c(HAP,HPA) %<-% as.numeric(H_A_VOC(AP)[1:2])
  
  # fitness function
  E_plant <- HAV
  E_animal <- 1-HVA
  
  # record results
  E[n,] <- c(n, HAV, (1-HVA), H_V, HPV, HVP, HAV, HVA, HAP, HPA, 
                   dFa, dFa_c, dFp, dFp_c, Fa_n, Fa_o, Fp_n, Fp_o)
  A_AP[[n]] <- AP
  A_PV[[n]] <- PV
}
```


```{r,eval = F}
## save output 
S_ind <- list(reps, A_PV, A_AP, E)
saveRDS(S_ind,'data/S_ind_100k.RDS')
```

```{r}
c(reps, A_PV, A_AP, E) %<-% readRDS('data/S_ind_100k.RDS')
AP_obs <- read.csv("data/AP_obs.csv", header = TRUE, as.is = TRUE, row.names = 1)
PV_obs <- read.csv("data/PV_obs.csv", header = TRUE, as.is = TRUE, row.names = 1)
AV_obs <- as.matrix(AP_obs) %*% as.matrix(PV_obs)

#plot_results
plot(-1, xlim = c(0,reps), ylim = c(0,1))
HPV <- H_A_VOC(PV_obs)[[1]]
c(HAV,HVA) %<-% as.numeric(H_A_VOC(AV_obs)[1:2])
HAP <- as.numeric(H_A_VOC(AP_obs)[[1]])

## plot observed values as lines
# conditional entropy for PV, AV and AP
abline(h = HPV, lty = "dotted", pch = 8) 
abline(h = HAV, lty = "solid", pch = 8)
abline(h = HAP, lty = "dashed", pch = 8) 
# fitness for animal and plant
abline(h = 1-HVA, col = "blue") 

s <- seq(1,reps,250)
points(cbind(s,E[s,"HPV"]), col = "red", pch = 24)
points(cbind(s,E[s,"HAV"]), col = "red", pch=  21)
points(cbind(s,E[s,"HAP"]), col = "red", pch=  22)
points(cbind(s,E[s,"E_animal"]), col = "blue", pch = 4)
```